### ISSUE TITLE
.exe missing in last release

### ISSUE THREAD

**Issue by mattthhh** [rcmdnk/vim_ahk#102]
Hello, in the last release (aka v0.14.0), the static build executable "vim_ahk.exe" is missing, is it planned to be released ?

**Comment by rcmdnk** [comment]
Thank you for pointing this out.

You are correct that the static build executable "vim_ahk.exe" was missing in the v0.14.0 release. 
Starting from v0.14.0, it was migrated to AutoHotkey v2, and there was an issue with the build process for the executable during this transition.

This has been resolved in the [v0.14.1](https://github.com/rcmdnk/vim_ahk/releases/tag/v0.14.1) release, where the executable is now included.

Could you please check the latest release
and please don't hesitate to let me know if you encounter any issues.

**Comment by mattthhh** [comment]
Yep perfect, thank you for your fast replies!
