### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by kbilsted** [rcmdnk/vim_ahk#104]
on windows 11 when either
* cloning and running the script using ahk 2.0.18 
* or download the latest release exe file 

 i get the following error

![image](https://github.com/user-attachments/assets/3cbdc953-0c2e-419b-a4fb-0ca1f2151876)

**Comment by rcmdnk** [comment]
Thank you for reporting this issue.

This could happen if you first launch vim_ahk.

It was fixed at v0.14.2.

Could you please try the latest main repository or exe from https://github.com/rcmdnk/vim_ahk/releases/tag/v0.14.2 ?

**Comment by kbilsted** [comment]
yes that works.
