### ISSUE TITLE
please let me to be contributor

### ISSUE THREAD

**Issue by satsaeid** [rcmdnk/vim_ahk#11]
Hi, thank you for your great project, I add a feature to this project.
supporting jj and تت instead of pressing Esc in both English and Farsi languages.
I can't push them to your git, I built a new branch, you can see it and if you want then you can merge it 
with your master branch.
best regard.

**Comment by rcmdnk** [comment]
Although I'm not planning to make any other contributors on this project,
I can check and merge it if you make pull request.

`jj` could be not proper for most of cases as I use it a lot to move down more than once below.

**Comment by satsaeid** [comment]
it's not instant and not so slow, it has a delay :)
please see it and if you like then merge it thank you
