### ISSUE TITLE
How to change jj to jk for enter normal mode?

### ISSUE THREAD

**Issue by BarryAndSherry** [rcmdnk/vim_ahk#15]
It can be configured using jj to enter normal mode, is there a way to change this jj key binding to jk?

**Comment by rcmdnk** [comment]
Thank you for the question.
Actually, this is what I have planned to be included,
as it is implemented in Mac version (Vim emulation for Karabiner-Elements: [Karabiner-Elements complex_modifications rules by rcmdnk](https://rcmdnk.com/KE-complex_modifications/), though it is "toggle" setting.)
And it seems easy to do therefore I included new options

* JK to enter Normal mode
* SD to enter Normal mode

They are disabled by default, but you can enable them as same as for JJ.
