### ISSUE TITLE
Typing cw does not work as expected

### ISSUE THREAD

**Issue by joelchretien** [rcmdnk/vim_ahk#16]
Steps to Reproduce:
1. Open a file with some text in it in MSWord
2. Navigate to the beginning of a word.
3. In command mode, type cw.

Expected:
The word under the cursor should disappear, and we should be in insert mode.

Actual:
The word under the cursor is merely highlighted, and we are still in command mode.

**Comment by rcmdnk** [comment]
Thank you for the feedback.

Currently, I'm traveling and, maybe will check it the week after the next week.

**Comment by joelchretien** [comment]
No worries.  Thanks for the tool.  Works great
