### ISSUE TITLE
accept escape sent by remapped caps key 

### ISSUE THREAD

**Issue by Konfekt** [rcmdnk/vim_ahk#24]
Thank you for this splendid script, everybody should know about it, spread the word!

Could it be made compatible with the script

https://gist.github.com/sedm0784/4443120

that remaps the caps-lock key to escape? If so, how least intrusively?

**Comment by Konfekt** [comment]
Putting `#Include  %A_LineFile%\..\vim.ahk` at the top of it rather made is stop working.

**Comment by rcmdnk** [comment]
I tried that gist but it doesn't work correctly for me.
(like the last comment, it seems that **Ctrl** is kept down)

Anyway, if it works for you and you want to change the mode to Normal by putting CapsLock,
following script may work:
https://gist.github.com/rcmdnk/90444480664aca0a5595cdd8bf6a365e

**Comment by Konfekt** [comment]
Thank you!

**Comment by Konfekt** [comment]
Thank you! Albeit it does not work. The caps key is only remapped if it vim.ahk is in normal mode. Other than that, it acts as caps.

**Comment by rcmdnk** [comment]
Does it work if you add `#if` after the first `return`?
(https://gist.github.com/rcmdnk/90444480664aca0a5595cdd8bf6a365e was updated like that)

**Comment by Konfekt** [comment]
Yes, thank you, it works now.

**Comment by rcmdnk** [comment]
Thanks for the validation.
I added the reset command of the condition at the end of vim.ahk.
Now you don't need  `#if` after including the file.

**Comment by Konfekt** [comment]
Thanks for pointing it out.

**Comment by Konfekt** [comment]
There ist also now https://github.com/ililim/dual-key-remap/releases which is worth a try.

**Comment by djhmateer** [comment]
Thanks to @Konfekt on the dual-key-remap I've got vim_ahk working well https://davemateer.com/2020/04/10/OneNote-with-Vim with the mapped escape key. @rcmdnk - this is a great script thank you!
