### ISSUE TITLE
ctrl-w in insert mode to delete the previous word 

### ISSUE THREAD

**Issue by stfl** [rcmdnk/vim_ahk#31]
I just installed the script and so far I am very pleased with the script.
I am very used to vim key bindings and I frequently use ctrl-w in insert mode to delete the previous word. 

In MS Word for example Ctrl-W closes the Window. I am asking you if it would be possible to implement deleting the previous word instead or is it impossible to overwrite default Windows key bindings?

If it is possible I might have a look at implementing it myself.

Thanks already.
Stefan

**Comment by rcmdnk** [comment]
A following code will enable Ctrl-W to delete previous word on MS Word:

    #IfWInActive, ahk_class OpusApp
    ^w::
      Send, {Shift Down}
      Send, ^{Left}
      Send, {Shift Up}
      Send, {Del}
    Return
    #If

You can put in your AHK file or at the end of vm.ahk if you use it directly.
Other deletion shortcuts are also can be implemented with the similar idea.
(While Shift Down, cursol move selects characters)

I think there are some AHK scripts to provide Emacs key bindings which may help you at Insert mode.

I also love to use Ctrl-W or other Emacs like key bindings as they are default at terminals,
and also on Mac applications.

I also want to include such a function to my Windows, so will check such scripts or make own necessary scripts once I can take time.
If I do, I will post details here.

**Comment by stfl** [comment]
thank you. I will add this to my script.

**Comment by stfl** [comment]
Ok, that is nice. I updated it also work in normal mode now. Which is better than accidentally closing the program by being in the wrong mode :D

**Comment by rcmdnk** [comment]
About Normal mode,
if you set `VimDisableUnused` to 3 (it is default),
all non-assigned keys including combination with Ctrl, Alt, Win are disabled,
so that Ctrl-w is also disabled normally.

If you want to use some keys (such Ctrl-s to save) even in Normal mode,
you need to change it as 2 (disable only single un-assigned keys) or 1 (does not disable any keys un-assigned).

You can change it from Task Bar Icon (see README).

**Comment by stfl** [comment]
thanks for the remark
