### ISSUE TITLE
Doesn't work '$' command in visual mode

### ISSUE THREAD

**Issue by mrDSide** [rcmdnk/vim_ahk#33]
When in visual mode press '$' caret goes to end of line withot marking.
Press '0' works as expected.

**Comment by rcmdnk** [comment]
Thank you for the report.

In my environment, '$' works as expected.
But I found that such 'W' (shift + 'w') or 'B' (shift + 'b') does not work for the visual mode.
Maybe the input shift and shift down for visual mode conflicts.
(Somehow '$' works in my environment...)

To fix this, I added some direct shift keys to these keys at visual mode.

With the latest master version, 'W'and 'B' work well as same as '$'.
I think '$' works on your environment, too. 

On the other hand, '^' does not work even after these fixes are introduced.
I will keep in mind this.

Anyway, try the latest version and check '$' on visual mode.

**Comment by mrDSide** [comment]
Awesome, thank you. Now everything works. The problem, i think, that i'm using custom Application, that doesn't works with keys as should, I tried 'emacs.ahk', then rewrote it to 'ergoemacs.ahk' and it was not so easy to deal in this application. At the moment i'd like add some extra emacs keybindings to your scritp.
Thanks a lot!
