### ISSUE TITLE
Split script into logically seperated multiple files

### ISSUE THREAD

**Issue by BlueDrink9** [rcmdnk/vim_ahk#34]
Would you consider accepting a PR that refactors out things like UI and settings into different scripts? Folds are ok but it is still unruly trying to jump between different parts of the script or find something you need to check or change, which leads to bugs and forgotten implementations.

Having multiple files `#include`d makes things much clearer to read the project.

For an idea of how this might work, see my fork.

**Comment by rcmdnk** [comment]
Thank you for the suggestion.

I agree that sometimes dividing into parts makes things clear,
especially for the testing.

On the other hand, I don't plan to split files for now,
as one file mode has more portability and I think it is better for users who just use the script.

**Comment by BlueDrink9** [comment]
Understandable about users that just use the script. However I imagine that most people would run the script from the cloned repo, so they can update it easier and track any changes. (If they have ahk installed,  they are probably developers who write other scripts too, right?)
Otherwise they would just use the exe.

Would this be solved if the exe was kept up to date? (ie through ci)?

**Comment by BlueDrink9** [comment]
Would you consider this some more now that the exe is being kept up to date? (Which solves the portability issue, to a large extent?)

**Comment by rcmdnk** [comment]
Yes.
I could not find the good practice to make a structure for AHK scripts,
but maybe we can start with vim.ahk at top and lib/xxx.ahk?

**Comment by BlueDrink9** [comment]
I concur. Feel free to check out my fork to see how I did it, and I believe one of the other contributors split it a different way.

For example, mappings should be separate from settings code.

Possibly separate out code for the `model` as well, like what the current mode is? May not have enough stored state for this to be worth it though

**Comment by rcmdnk** [comment]
ok, I'll employ the policy for development.
As you mentioned, separated into each mode may not only make the code seems better 
but also give some futures available.

**Comment by BlueDrink9** [comment]
Can I do this and open a PR? Or are you happy to? (I really want this done, especially after the work I just did)

**Comment by rcmdnk** [comment]
Closed as #40 was closed.
