### ISSUE TITLE
how can I use this in chrome?

### ISSUE THREAD

**Issue by huxianglong** [rcmdnk/vim_ahk#36]
Hi, I'm wondering whether this can be used in google chrome? Thank you.

**Comment by rcmdnk** [comment]
Yes!
Please open the GUI setting window:

* Right-click AutoHotKey (vim_ahk) icon in the task tray
* VimMenu->Settings

Then you can see **Applications**.
(see [README.md](https://github.com/rcmdnk/vim_ahk/blob/master/README.md))

If you want to enable vim_ahk on Google Chrome, then add `ahk_exe chrome.exe`
in **Applications**.

You can check ahk_exe of applications by using Window Spy of AutoHotKey (again, you can find by right-clicking the icon)

**Comment by huxianglong** [comment]
definitely one of the best ahk scripts I've used! Thank you very much!
