### ISSUE TITLE
'dd' command

### ISSUE THREAD

**Issue by eucmanlee** [rcmdnk/vim_ahk#4]
Hi,

Thank you for sharing your script. It works perfect with my ten-less keyboard. :-)

In the mean time, I found that when I use 'dd' - cut a line in my MS word, 
the cursor also deletes the first letter of the next line. 

do you have any idea how I can fix this problem?

thank you for your help in advance.

Best Regards

Eucman

**Comment by rcmdnk** [comment]
Hello,

Thank you for the report.
I confirmed the behavior that Word and PowerPoint have different behaviors for `End` button,
which covers even line break symbol in these application.

I updated the script for these applications.
Could you please try with new one.

There could be more differences in these applications,
so I'm appreciate if you could report anything wrong when you find it.

I have only Windows 10 & MS Office 2007, and it could be different in other versions.
But I think it is same at least for Windows 10 environment.

**Comment by eucmanlee** [comment]
Hi,

Brilliant! the script is now working just perfect ^^

thank you for sharing this !!!

Note: my machine has windows 7 and MS office 2013 (word and powerpoint)

Best Regards

**Comment by eucmanlee** [comment]
And as for a note, it works on my power point when I change the script as below;

-------------------------------------------
; GroupAdd VimGroup, ahk_class PP12FrameClass ; PowerPoint
GroupAdd VimGroup, ahk_class PPTFrameClass ; PowerPoint
-------------------------------------------

**Comment by rcmdnk** [comment]
Thanks for the feedback.
I changed these definitions like:

    GroupAdd VimGroup, ahk_exe POWERPNT.exe

ahk_exe name seems more stable than ahk_class name.
ahk_class is only for the window, while ahk_exe is for entire application.
This change will enable vim mode even at some pop up diagrams (e.g. save file).
I think it is fine for the usage.
