### ISSUE TITLE
Let's talk features

### ISSUE THREAD

**Issue by nnako** [rcmdnk/vim_ahk#41]
Hi,

thanks for this great approach to provide system-wide usage of vim keybindings. After a long journey, I finally found your implementation (though should have been easily found by searching for `vim` and `autohotkey` within GitHub). There are some other solutions out there, though, which don't seem as far as your one.

I was wondering if there was a plan for adding some features:

- **show the COMMAND LINE after pressing `:`** . In order to be able to visually adjust the input, the user might be happy to have some kind of feedback.
- **provide application-specific key bindings** . As far as I see the code, there is _one_ set of keybindings for each mode over _all_ possible applications. This makes it impossible to include e.g. non-text-applications like mindmaps or other graphically oriented programs (yEd,...). Those applications would require a specific (different) translation for example of "hjkl", fitting to the specific task "go to the right bubble" or "go backwards in time". I could think of adjusting the overall code structure to render it modular in the described sense. New applications could easily be added even with different key bindings.
- **re-implement the functionality in e.g. AutoIt scripting language** . As AutoHotKey does not seem to be easily maintainable when the codebase grows and the number of developers join the team, I was thinking of proposing a more "language"-like implementation language like AutoIt. With a clear and concise syntax and better facilities for testing. As the functionality is comparable, this might be an option.
- **integration of a search functionality using `/`** . In order to skim through lange texts without having to switch to the application's native search functionality, a built-in one would be nice. This would be one feature which could profit from a per-application-keybinding (see above), as search / find functionalities mostly differ in applications. Of course, a next step might be the provision of Regular Expressions within the search...
- ...

I would love to participate in the further development, heading towards a _complete_ vim framework in 2030 ;-) . Therefore, the code structure would have to be modified, today.

Looking forward to hearing from you. What do you think?

Thanks.
Nnako

**Comment by rcmdnk** [comment]
Thanks for the comment.

> show the COMMAND LINE after pressing `:`

Current vim_ahk has only commands of max 2 words (`wq`) and 
I think the additional popup is too much.
You can check if the current mode is `Command` or not by the tray icon.
But it is not so difficult and I can try to make a popup.

In the future, if we want to have longer commands,
then maybe we can implement a popup input window to execute them.

For now, I'm satisfied with the current commands,
but if you have ideas of commands, then please let me know.

> provide application-specific key bindings

vim_ahk has some application-specific workflows like:
https://github.com/rcmdnk/vim_ahk/blob/master/vim.ahk#L57

They are tiny fixes, but you can add some like that.
It may be difficult to establish a fully customizable from GUI or external settings.

If you have some specific applications, I can try to implement them.

> re-implement the functionality in e.g. AutoIt scripting language

This project started from tiny key mappings and AHK was best for it.
It could be a more flexible application if another language is used,
but I have not worked with AutoIt...
I'm interested in upgrading this project and if such AutoIt makes better, then I can follow up, but maybe I don't have enough time to do now...

> integration of a search functionality using /

Do you mean `a built-in` as a built-in of vim_ahk?
I don't have an image of how to implement it.

Currently, vim_ahk has search functionality at Normal mode with `/`,
which open `Ctrl-f`.
It works on most of the applications of Windows.
Of course, some applications have different search functions.
If you know any applications which use other than `Ctrl-f` to start the search,
I can implement them at
https://github.com/rcmdnk/vim_ahk/blob/acd987b668609a9958271a3312eaa8a830f51ff2/vim.ahk#L1469

I agree that it is good to have a function to update it by users themselves easily.
I'm welcome to have a new idea for it.

**Comment by nnako** [comment]
Hi, and sorry for my late reply...

Thanks for your detailed response. I think, now I know where it is heading with this project. My intention was to maybe make it more "modular", so e.g. not to have to change the code base each time a user has a new and different key binding for his new application, but to provide e.g. an initialization file where every user can decide themselves which key bindings should be active for which application.

I think, this kind of concept will not be in focus here, eh?

Thank you anyway.

**Comment by nnako** [comment]
Hi again ;-)

would it be possible for you to provide a kind of "class diagram" for the project? or something with similar information content? some kind of documentation where I could see the program's structure elements connected to each other? I'm trying to unserstand the code base so that I might be able to localize appropriate points where to try some modifications.

Thanks.

**Comment by rcmdnk** [comment]
There is no documentation of the concept, sorry.
In addition, the structure of the code was changed recently.

The rough concept is:

- vim.ahk: the main script should be called by AHK directly or from other scripts.
- lib/*.ahk: scripts to define classes. All functions should be implemented in the classes.
- lib/bind/*.ahk: scripts to define key bindings.
- lib/util/*.ahk: other utilities.


For now, vim_ahk has some fixes for particular applications:
Microsoft Office, OneNote (before Win10), Visual Studio, NotePad, and Explorer.

For them, groups are defined:
[vim_ahk/vim_ahk.ahk at v0.7.2 · rcmdnk/vim_ahk](https://github.com/rcmdnk/vim_ahk/blob/v0.7.2/lib/vim_ahk.ahk#L49)

An example fix for OneNote:
[vim_ahk/vim_move.ahk at v0.7.2 · rcmdnk/vim_ahk](https://github.com/rcmdnk/vim_ahk/blob/v0.7.2/lib/vim_move.ahk#L82)

About your concept, maybe we can add another group like `GroupSpecial` in addition to `GroupName`.
Then, implement it as same as `GroupName` so that users can update the list from the setting panel.

Then add key bindings for `GroupSpecial`.

Maybe I have not fully understood what you want to do,
don't hesitate to tell me what you want
and any kind of ideas is welcome!

**Comment by nnako** [comment]
Hi @rcmdnk and thanks for the information and your openness for change ;-)

It took me some time to finally get back to the point where we were one year ago. I now understood a bit more of the structure of the project. I could imagine to contribute some features after discussing them here in the issues / features area. As you consequently use classes, the difference to "standard" languages does not seem too huge. Just some of AHK's specifics when defining Hotkeys (specific double-colon notations), accessing windows (using internal global variables like "ahk_group"), non-standard handling of strings or calling special functions (calls without braces but with commas) must be learned.

One last question: what development environment do you use and do you recommend? There seem to be various possibilities:

- AHK-Studio which has a single-step debugger and other features
- Notepad++ together with a suitable plugin (originally for PHP dev)
- ...

How does your own development environment look like?

**Comment by rcmdnk** [comment]
I'm vimmer so that I'm using Vim (recently, NeoVim).
For AHK, I add a plugin, [sheerun/vim-polyglot](https://github.com/sheerun/vim-polyglot), for the syntax highlight.

On the other hand, if you don't have any preferred editor,
it seems AHK-Studio is a powerful editor for AHK scripts and it is good to start with it.

**Comment by nnako** [comment]
I'm a vimmer myself :-) . Thanks for your answers. But how do you debug your AHK code? AHK-Studio seems to provide a single-step-debugger (with breakpoints and watches,...) . I couldn't get AHK's debugger it to run properly when trying it on your code base for VIM_AHK. Don't you use a debugger while coding / testing? Is it just a special setting I miss in AHK-Studio? Or are you using some kind of other plugin for vim which provides debugging? Mere syntax highlighting does not really help when it is about digging for bugs.

Any further hints?

**Comment by rcmdnk** [comment]
Actually it is difficult to debug such a scripting language.
I tried  AHK-Studio, but it may not fully help you.

One of the ways of debugging is a bulding exe file using build.bat.
It should detect obvious syntax issues,
though it can be detected by running the script, too.

To checking existing functions,
@BlueDrink9 prepared tests in [tests](https://github.com/rcmdnk/vim_ahk/tree/master/tests) folder.
(See the bottom of [README.md](https://github.com/rcmdnk/vim_ahk/blob/master/README.md)
It can cover the basic functions.

**Comment by BlueDrink9** [comment]
Yeah, AHK is a poor lang to build software in because it doesn't have a lot of tools to help you. My vim ahk setup:

```vimscript
Plug 'kovetskiy/sxhkd-vim', {'for': 'sxhkdrc' }
" Adds syntax highlighting.
Plug 'vim-scripts/autohotkey-ahk', {'for': 'autohotkey'}
" Adds indent. Included in polyglot.
Plug 'https://github.com/hnamikaw/vim-autohotkey', {'for': 'autohotkey'}
Plug 'https://github.com/huleiak47/vim-AHKcomplete', {'for': 'autohotkey'}
" c-x o to complete from ahk syntax list
setl omnifunc=ahkcomplete#Complete

nnoremap <buffer> <leader>r :!start /b autohotkey "%:p" <cr>

```

If you can get a good debug workflow going, that is marvellous. I usually use tooltip or msgbox debugging, which is pretty tedious but AHK doesn't provide many better tools afaik.

Enable `debugMode` in the top of the script (enables `#warnings`, amongst other things) for more messages.
