### ISSUE TITLE
v-mode : selecting texts by moving the cursor (i.e. use key 'l')

### ISSUE THREAD

**Issue by eucmanlee** [rcmdnk/vim_ahk#5]
Hi ,

thank you for sharing the script. 

while using the ahk script in both MS word and Notepad ++, I just realized that 
v model + cursor move using key 'hjkl' is not working so well.

for instance, if I put key 'l' in v-mode, I can only select 3 or 4 characters in max (in MS word).
If I put key 'l' longer, then, the word will turn the selected into large 'L' characters. 
The same happens in Notepad ++ as well.

any idea?

thanks for your help in advance.

**Comment by rcmdnk** [comment]
Thank you for the report.

Actually this is one of things which I have not solved, yet.

Sometime the key repeat of keys bound by AutoHotKey is not working well,
if the binding has several keys.

You can use `w` or `$` to move faster than `l`, as vimer.
(somehow, `w` repeat works much better than hjkl, there could be a hint to solve this...)

**Comment by eucmanlee** [comment]
I C.

Yes, w or b works perfect. :-)
