### ISSUE TITLE
Settings not being saved

### ISSUE THREAD

**Issue by mike-lloyd03** [rcmdnk/vim_ahk#50]
When I make changes to the Application list, they are not saved next time I start up the script. When I click `About`, it says I should have a settings file at `$HOME/App Data/Roaming/Auto Hotkey/vim_ahk.ini` but there is not one there.

**Comment by rcmdnk** [comment]
Thanks.
Indeed, it seems broken, sorry.
The current file makes `this.IniDir` in the same directory of the main AHK file and the file save fails if the directory under the Roaming does not exist.
I'll fix.

**Comment by rcmdnk** [comment]
Ok, the bug was implemented from v0.6.0 (~Jan 31).
I fixed it in v0.7.4.
Could you please update vim_ahk and check it?

**Comment by mike-lloyd03** [comment]
Looks good! Thanks so much.
