### ISSUE TITLE
Motions only repeat last hotkey

### ISSUE THREAD

**Issue by nwilleyltk** [rcmdnk/vim_ahk#51]
How to reproduce:
* Open Notepad.
* Enter insert mode
* Type: This is a test
* Enter normal mode
* Type the motion d4b or alternatively 4db
*  'test', will be deleted and the cursor will skip to the front of the line. You will now see 'This is a' instead of the expected empty line.

It seems possible to use A_PriorHotkey along with A_Hotkey to enhance the repeat function to match vim's motions. 
https://www.autohotkey.com/docs/Variables.htm#A_PriorHotkey

**Comment by rcmdnk** [comment]
Thanks for the report.
In my case, `d4d` deleted all line. It should be fine.
But if I write more than 4 lines, and do `d4d`, it deletes only 1 line.

So the repeat implementation seems broken in any case.
I wil check.

On the other hand, in your case, simple `dd` works fine? (deletes all line or not?)

**Comment by nwilleyltk** [comment]
I can confirm that `d4d` deleted the entire line.  Yes, dd would work to delete the line, which would be the normal way to delete the line.  This was only an example to show that using the `w`, `b`, `e`, etc., combined with the motion doesn't function as in vim.   Say I wanted to delete only the last 3 words after typing them, I'd normally do `d3b` (or `3db`, both work the same in this case in vim).

[Here's the vim documentation for motions. ](http://vimdoc.sourceforge.net/htmldoc/motion.html)

**Comment by rcmdnk** [comment]
ah, sorry, you mentioned d4`b`, instead of d4`d`.
ok, I confirmed.
As you said, it seems all motions with `d` delete in only the first motion, and just move remaining times.
Let me check...

**Comment by rcmdnk** [comment]
Multi move yank/delete/change was fixed partly.
Now (with the latest master) `d3b` deletes 3 words before the cursol correctly.

But the function with Up/Down (e.g. `d3j`) does not work.
Also I found `3dd` deletes only 1 line.

I'll check...

**Comment by rcmdnk** [comment]
OK, now (v0.7.5) `d3j` deletes current lien + 3 lines below.
`3dd` deltes 3 lines including current line.
