### ISSUE TITLE
Automatic detect Textbox

### ISSUE THREAD

**Issue by quyleanh** [rcmdnk/vim_ahk#54]
I just wander that could you supports detect when clicking to a textbox of any Windows apps? My wish is I want to use terminal bindkey when typing in textbox. For example, Ctrl + E = End, Ctrl + A A = Home...

**Comment by rcmdnk** [comment]
I'm not sure if AutoHotkey can detect `input` status at Windows.
Normally it can detect on which application you are working on,
but more details in apps (if it is at text box or not) may be not detectable.

On the other hand, Ctrl-A at Windows is the shortcut often used to select all text.
Ctrl-E is also another shortcut to centering (though I've never used it...)

In addition, they are **Emacs key bindings**, so I think they should not be in this script.

Maybe you can implement in your main AutoHotey script like:

	$^a::Send, {HOME}
	$^e::Send, {End}
	; To use original Ctrl-a/e shortcut, it is better to asign to Alt-a/e
	$!a::Send, ^a
	$!e::Send, ^e

**Comment by quyleanh** [comment]
Thank you for your recommendation and your amazing AHK script as well.
I will close this issue.
