### ISSUE TITLE
Can not change Vim variables (VimGroup, VimRestoreIME, etc...) from an external script once the setting is saved

### ISSUE THREAD

**Issue by rcmdnk** [rcmdnk/vim_ahk#56]
vim_ahk's setting variables can be set from an external script which includes vim_ahk.

## Problem

* If nothing has been saved, then setting variables in the external script are reflected correctly.
* If the user opne the setting menu and push `Reset`, then the settings are changed to the default variables of vim_ahk (not the user definition).
* After that, even if the user restart the script, user variables in the external script can not be read.

## What should be

* `Reset` restores settings of the user definition in the external script.
* Or add `Default` button to reset to vim_ahk default, and set `Reset` to restore user variables.

**Comment by rcmdnk** [comment]
> * Reset restores settings of the user definition in the external script.

Implemented at v0.8.0.

**Comment by rcmdnk** [comment]
@tkishiro 
suggestion ありがとうございます。
とりあえず今回の変更では単純に起動時にユーザー指定変数で
デフォルト変数を上書きするような変更にしました。
これによって`Reset`の動作もユーザー定義を優先してそれに戻す、という動作になります。

**Comment by tkishiro** [comment]
@rcmdnk 
なるほど。１行で綺麗に解決できるんですね。
コメントありがとうございます。
