### ISSUE TITLE
'dd' doesn't work as expected in Obsidian program

### ISSUE THREAD

**Issue by Gramoteev** [rcmdnk/vim_ahk#59]
Hello, In Obsidian (my main note-taking tool) https://obsidian.md/

Any commands with 'd' ('dd', 'D', 'd^', 'd$') delete all text in the file and close it.

Is there any way to fix this?

**Comment by rcmdnk** [comment]
I tried vim_ahk on obsidian.md,
and all commands including `dd` work.

`ahk_exe Obsidian.exe` was added to the Application list.

How do you launch vim_ahk?
If you have your own AutoHotkey script and call vim_ahk from there,
then some other AHK settings may conflict with vim_ahk.
If so, could you please try to launch vim_ahk directly,
or try [executable](https://github.com/rcmdnk/vim_ahk/releases),
after stopping your AHK script.

**Comment by Gramoteev** [comment]
Thanks for your reply. You gave me an idea and I discovered how to repeat this bug. for this, it is enough to set the ctrl - x command to delete current file in Obsidian Settings -> Hotkeys.

and then "dd" deletes the file
but I don't understand why exactly the command "ctrl - x" works like this

thank you very much for your response. ahk_exe - exilent tool.

**Comment by rcmdnk** [comment]
> set the ctrl - x command to delete current file in Obsidian Settings -> Hotkeys.

Ah, this makes such a bevavior.
AHK is kine of the key mapper,
and all of these commands ('dd', 'D', 'd^', 'd$') are mapped to key combinations including `Ctrl-X`, like:

`d`+`d` -> `Home`+`Shift-End`+`Ctrl-x`

vim_ahk has been developed based on such Windows' basic key shortcuts.
Therefore, please be careful when you set such hotkeys (especially Ctrl-z/x/c/v) at the applicatoins.
