### ISSUE TITLE
Force Insert mode in the search modal window

### ISSUE THREAD

**Issue by nadya-p** [rcmdnk/vim_ahk#6]
When I search using / in some app (MATLAB in my case), usually a modal window pops up. In this modal window, the mode is still "Normal", whereas it would be more convenient to automatically switch to "Insert" mode in order to enter the search string without additional "i" key.

Placing
`VimSetMode("Insert")`
just before `Return` of `; Search {{{` function doesn't fix the problem in my case.

Otherwise, thanks for an excellent script!

**Comment by rcmdnk** [comment]
ok, I agree your comment.
I put ` VimSetMode("Insert")` at Search mode being launched.
