### ISSUE TITLE
Using "O" for new line always enters a tab to what ever word is on that line - can this be changed?

### ISSUE THREAD

**Issue by lundeen-bryan** [rcmdnk/vim_ahk#62]
First I'm new to understanding ahk so if this is an easy fix I appologize. 

Example:
This is the line one.
This is the line two. 

Given that my cursor is anywhere on line two, 
And I press shift+o to give a capital "O"
Then the cursor should create a new blank line above line two and shift line two down making it line three.

Instead when I press "O" it shifts line two down to line three but places the cursor on line three followed by a tab then the text for line three. Line two at this stage is blank. Then I have to delete the tab character, change to normal mode and go up to line two then press "i" to start insert mode. 

Is there a way to change this behavior so that it shifts line two down to line three with no tabs in front, then places the cursor on line two at the beginning of the line and be in insert mode?

**Comment by rcmdnk** [comment]
It is not expected behavior.

It should just move the line two to the line three, and make a new blank line at the line two, w/o tab.

I just tested on Notepad, Wordpad, and Word,
and "O" make just a new blank line at line two.

On which application are you working on?
Could you please try on some other applications?

**Comment by lundeen-bryan** [comment]
I'm so sorry that I didn't take those steps. I realized it works fine in anything except Dreamweaver code view. Once I realized it was Dreamweaver's settings, I turned off auto-indent and that fixed the problem. 
Thank you so much for the prompt reply and help.
