### ISSUE TITLE
[Enhancement] Visual indicator of normal/insert mode (not in notification tray)

### ISSUE THREAD

**Issue by traycerb** [rcmdnk/vim_ahk#64]
I hide my taskbar, so it becomes hard to know which mode I'm in.  Is there a way to show the normal/insert mode status outside of the notification tray?

I tried making my own Vim emulation with ahk, and while I abandoned it due to this one being much more fully featured, one thing I did do was have a visual indicator of status.  In my Vim emulation attempt, I used CapsLock as my mode indicator and toggle, and I used the following simplistic code to show the state.  

Would it be possible to integrate something like this into vim_ahk?  I haven't looked at vim_ahk's source, so if you think it's possible, but can't devote the resources, could you please point me to the code or logic that would be useful in implementing this.  Thanks, the program is great so far in my limited testing.

```
#SingleInstance force
#NoEnv

Menu, Tray, NoStandard
Menu, Tray, Add, Exit, QuitScript


Gui, +AlwaysOnTop +ToolWindow -SysMenu -Caption +LastFound
Gui, Font, caf001e s12 bold, Verdana ;changes font color, size and font
Gui, Color, af001d ; changes background color
Gui, Add, Text, ,CAPS LOCK ON
WinSet, TransColor,af001d

Loop
{
	GetKeyState, CapsState, CapsLock, T
	If CapsState = D
	{
		Gui, Show, % "x" . (A_ScreenWidth/1.2) . "y" . (A_ScreenHeight/1.1) . " NoActivate"		Menu, Tray, Icon
	}
	Else
	{
		Gui,  hide
	}
	Sleep, 100
}

QuitScript:
ExitApp
return
```

**Comment by rcmdnk** [comment]
Maybe you can try to change the status tooltop a bit little.

Go to the 
https://github.com/rcmdnk/vim_ahk/blob/master/lib/vim_state.ahk

and edit [Status function](https://github.com/rcmdnk/vim_ahk/blob/38c1c6c83540c7597f6be9651060ec3e55cb82ea/lib/vim_state.ahk#L35) like:

```diff
  Status(Title, lines=1){
    WinGetPos, , , W, H, A
-    ToolTip, %Title%, W - 110, H - 30 - (lines) * 20
-    this.Vim.VimToolTip.SetRemoveToolTip(1000)
+     ToolTip, %Title%, 0, 0
+    this.Vim.VimToolTip.SetRemoveToolTip(1000000)
  }
```

and add following line in [ __New function](https://github.com/rcmdnk/vim_ahk/blob/38c1c6c83540c7597f6be9651060ec3e55cb82ea/lib/vim_state.ahk#L2) of the vim_state.ahk:

```
CoordMode, ToolTip, Screen
```

Then launch the vim_ahk, and open the settings of vim_ahk from the task tray icon, 
and set `Verbose level` to 2.

This will make a (pseudo) permanent tooltiop at the left up of the desktop, which shows the mode of vim_ahk.

Original `Verbose level`=2 shows the tooltip at the right bottom of the current window and it disappears in a 1 sec.

One of the problem if you set like above, the tooltip will not removed even if you are working on applications on with vim_ahk is not enabled.

Maybe you can implement a loop function to check applications
and reset tooltip if the application is not a vim_ahk app.
(sorry, currently vim_ahk does not have such a function.)

Could I answer to your question?
Please don't hesitate to give a comment
if what you want to do is something differenct from this!
