### ISSUE TITLE
Denylist of applications, instead of Allowlist

### ISSUE THREAD

**Issue by rcmdnk** [rcmdnk/vim_ahk#66]
Currently VimGroup is the Allowlist.

Some may want to enable vim_ahk for the most of applications
and define the Denylist instead of Allowlist.

* Maybe just add both list and use each if any of applications are included
* or add checkbox to choose one of them and have only one application list (setting menu can be simplified)

**Comment by almogtavor** [comment]
I think that it's very important to allow one to use vim ahk on all applications so the denylist is an important feature. One list with a checkbox should do the work in my opinion, at least for the beginning.

**Comment by rcmdnk** [comment]
OK, now vim_ahk has an option of VimAppList.
You can find it in the setting window as `Application list usage` just above of `Application` list in the bottom.

You can choose one of:
* All
* Allow List
* Deny List

If you choose `All`, vim_ahk is enabled on all applications.
If you choose `Allow List`, it works as before.
If you choose `Deny List`, the application list works as deny list.
