### ISSUE TITLE
[Enhancement] Add vim's "ciw" support

### ISSUE THREAD

**Issue by 0x7FFFFFFFFFFFFFFF** [rcmdnk/vim_ahk#72]
It would be nice if we can use `ciw` in vim_ahk. I use this shortcut very often when programming. Thank you.

**Comment by rcmdnk** [comment]
Thanks for the idea!
It is probably possible in some cases.
I'll try it later.

**Comment by rcmdnk** [comment]
New key bindings in the Normal mode have been added at [v0.11.0](https://github.com/rcmdnk/vim_ahk/releases/tag/v0.11.0).
Please try it!

* `viw`: Select the current word.
* `yiw`: Copy the current word.
* `diw`: Delete (Cut) the current word.
* `ciw`: Change the current word (Cut and enter the Insert mode).

Note:

* For the normal sentence, they select the current word + spaces in front of the next word.

* It works better on the Wordpad than the Notepad especially if the word is surrounded by symbols.

Examples (the cursor position is `|`):

|Situation|Selected characters|
|-|-|
|`abc e\|fg  hij`|`efg　`|
|`print("a\|bc")`|`abc` on the Wordpad, `("abc")` on the Notepad.|
|`abc/d\|ef/ghi`|`def` on the Wordpad, ``abc/def/ghi` on the Notepad.|

**Comment by 0x7FFFFFFFFFFFFFFF** [comment]
Thank you so much, and this is so useful!
