### ISSUE TITLE
Normal mode 'a' behavior in the end of line

### ISSUE THREAD

**Issue by happyTonakai** [rcmdnk/vim_ahk#74]
In normal mode, when there is another following line, pressing `a` in the end of the line will jump to the next line. 

Expected behavior is to enter insert mode at the end of current line (same as pressing `i` here)

For example:

```
test text
new line.
```

When cursor is at the end of the first line, after pressing `a` the cursor will jump to the head of new line.

**Comment by rcmdnk** [comment]
Thanks for the report.

The key `a` is bound to `Cursor Right` + `Enter Insert mode`.
Thus, when you use it at the end of a line, it goes to the next line.

Currently, I don't know how to detect the end of a line at AHK.
All ideas and suggestions are welcome!

**Comment by happyTonakai** [comment]
I'm new to AHK, but after googling I think this maybe helpful: 
https://www.reddit.com/r/AutoHotkey/comments/4ma5b8/identifying_end_of_line_when_typing_with_ahk_and/

**Comment by rcmdnk** [comment]
Thanks!
I wasn't aware of such a hack using a clipboard.
It may also be used for other purposes.

I'll give it a try.

**Comment by rcmdnk** [comment]
I think this works well.
Please try v0.11.1!
https://github.com/rcmdnk/vim_ahk/releases/tag/v0.11.1

**Comment by happyTonakai** [comment]
Thanks for your working. But I think you shouldn't send `{Left}` if `Vim.CheckChr()` returns `true`, which causes the insert mode doesn't activate at the end of the line, but one character before the end. I've changed it to
```
a::
  if(not Vim.CheckChr("`n")){
    Send, {Right}
  }
  Vim.State.SetMode("Insert")
Return
```
which works well for me.

**Comment by rcmdnk** [comment]
you are right.
sorry, I was confused.
`{Left}` is needed to reset the highlight but it was implemented in CheckChr function.

Now it should work with v0.11.2.

**Comment by happyTonakai** [comment]
OK. I'll close this issue then. Thank you.

**Comment by rcmdnk** [comment]
@happyTonakai 
As it changes the behavior of `a` and it may make the feelings worse it in some cases
(because there is a short sleep time to use the clipboard),
I added an option to enable this behavior and it is disabled by default.

sorry to change in a short period.


![20220214_win_5945-00](https://user-images.githubusercontent.com/1818935/153773049-3d067cf1-c93a-4679-ab27-dbbe5bc261ef.jpg)
