### ISSUE TITLE
[Feature request] Send ESC by ESC at the insert mode and then enter the normal mode

### ISSUE THREAD

**Issue by happyTonakai** [rcmdnk/vim_ahk#75]
Using IME for CJK languages when typing pinyin (Roman letters for Japanese), we use number keys to select candidate words and use ESC to cancel the entire input. 

![1](https://user-images.githubusercontent.com/21305646/152757964-3605c8d0-4469-4234-8425-23e54edb0c8f.png)

After pressing ESC there will be nothing left.
 
However when vim_ahk is running in insert mode, I type some words and I want to press ESC to cancel the input, there are some remaining pinyin like this:

![2](https://user-images.githubusercontent.com/21305646/152758253-8fec6d35-9b8c-46b1-b18d-9bee73e20aaa.png)

So I think is it possible to send ESC at insert mode and then enter the normal mode?

(btw, I found that it works as expected in notepad++ and notepad3, but not working in msword and MATLAB, I don't know why)

**Comment by rcmdnk** [comment]
Actually it is difficult to treat IME with vim_ahk.
I'm using Japanese IME, and there are some tricks.

Using https://github.com/rcmdnk/vim_ahk/blob/master/lib/util/vim_ime.ahk,
I map the key `^[` (to enter the normal mode, as ESC) like: https://github.com/rcmdnk/windows/blob/9ce79d7131b2ac2c3c34c8eb29d3db7b556b4f2a/AutoHotkey.ahk#L81

If the IME is trying to converting characters, `^[` just cancels it and continue the insert mode.
But sometime it works w/o this setting.
I think AutoHotkey assumes IME as the current app in this case.

You may try to use long press ESC.
If you push ESC more than 0.5sec, vim_ahk sends normal `ESC` at the insert mode.

So if you can cancel the input by pressing `ESC` more than 0.5 sec, and then push `ESC` shortly if you want to enter the normal mode or continue to write in the insert mode.
