### ISSUE TITLE
How can I make this work for SSMS? it used to work until now

### ISSUE THREAD

**Issue by lundeen-bryan** [rcmdnk/vim_ahk#79]
your branch of vim.ahk is great and I used to use it on SSMS but today it won't recognize the window. The title of the tab is SQLQuery.sql which is default but when I put that in the vim.ahk settings, it doesn't recognize the window. It works to recognize OneNote and other windows but now this application. Any ideas on how to make it work? is there a way to make the settings recognize "startswith(SQLQuery)" for example?

**Comment by rcmdnk** [comment]
To use `startswith`, set `SetTitleMatchMode` as `1`.

![20220424_win_131649-00](https://user-images.githubusercontent.com/1818935/164956374-ec2b2b7a-1685-4fcd-adcc-868a282dd393.png)

`SetTitleMatchMode`:
- 1: Start with
- 2: Contain
- 3: Exact match
- RegExp: Regular expression

But the default is `2`, so if you have not changed it, it should work if the title contains `SQLQuery.sql.

Could you check the window by Window Spy?

![20220424_win_13848-00](https://user-images.githubusercontent.com/1818935/164956224-21a26228-4847-45c2-a274-9146b7983f42.jpg)

![20220424_win_13926-00](https://user-images.githubusercontent.com/1818935/164956231-4f49b9a9-9a57-4dae-9932-d0688e43b9b7.jpg)

If it shows that the title contains `SQLQuery.sql`,
you may try to set `Slow` at the second column of SetTitleMatchMode.

On some apps, it fails to get the title with `Fast` mode.

Ref: https://www.autohotkey.com/docs/commands/SetTitleMatchMode.htm

The default is `Fast`, but it works comfortably even with `Slow` mode at the most of recent machines.

Or you may try to use `ahk_class` or `ahk_exe`.

**Comment by lundeen-bryan** [comment]
Thank you so much for the quick reply, all of your tips work great!
