### ISSUE TITLE
the 'enter' key doesn't work in normal mode, onenote 2021

### ISSUE THREAD

**Issue by shakeitbaby** [rcmdnk/vim_ahk#88]
When I press enter in normal mode, a new line will be output

**Comment by rcmdnk** [comment]
Currently Enter is not disabled.
On some applications, you may want to move by hjkl and select (or push the button) under the cursor.

At the editor, vim movement should be going to the first character of the next line.
Although it is not possible to move to the fir st character, you can change `Enter` to move to the next line.

Prepare the following **myscript.ahk** in the same folder where vim_ahk folder exists:

```ahk
#Include %A_LineFile%\..\vim_ahk\vim.ahk
Return

#If Vim.IsVimGroup() and (Vim.State.IsCurrentVimMode("Vim_Normal"))
Enter::
  Vim.Move.Move("j")
  Vim.Move.Move("^")
Return
```

If you launch the **myscript.ahk**, then `Enter' will move the cursor to the next line in the normal mode.



It may be good to prepare the group "Editor" on which `Enter` works like above.
Let me put it in the to do list.

**Comment by shakeitbaby** [comment]
Thank you very much

**Comment by rcmdnk** [comment]
@shakeitbaby 
From v0.12.1, `Enter` moves the cursor to the begining of the next line for editor applications.
(To be accurate, for other than Explorer and Q-dir).

**Comment by shakeitbaby** [comment]
I've tested it, it's perfect, thank you
