### ISSUE TITLE
Migration to AutoHotkey v2

### ISSUE THREAD

**Issue by rcmdnk** [rcmdnk/vim_ahk#95]
[Quick Reference | AutoHotkey v2](https://www.autohotkey.com/docs/v2/)

**Comment by GoldyWang2013** [comment]
good job!

**Comment by GoldyWang2013** [comment]
when will the v2 Version published?

**Comment by rcmdnk** [comment]
sorry, it has not been started, yet.

For now, if you can run vim.ahk directly with the latest AutoHotkey which include both v1 and v2 binaries.

**Comment by GoldyWang2013** [comment]
anticipate, and for now, it is good enough...

**Comment by rcmdnk** [comment]
@GoldyWang2013 

[v0.14.0](https://github.com/rcmdnk/vim_ahk/releases/tag/v0.14.0) was released for AutoHotkey v2.
Current master branch is also updated for v2.
