### ISSUE TITLE
Typing 'f' key in normal mode types out f

### ISSUE THREAD

**Issue by Shr4pNull** [rcmdnk/vim_ahk#96]
Typing 'f' key in normal mode types out f. Is that behaviour right? It should find the next instance of a char in the line?

I've tried the release in windows 10 & windows 11 environments and this still happens - only tried it in onenote and notepad.exe

**Comment by rcmdnk** [comment]
Could you please check `Disable unused keys in the normal mode` option.

Settings window can be laucnhed by the right-click menu of the task tray icon (find VimMenu-Settings in the list), or Ctrl-Alt-Shift-v.

> https://github.com/rcmdnk/vim_ahk?tab=readme-ov-file#gui-option-setting-window

![SnapCrab_NoName_2024-3-13_8-22-52_No-00](https://github.com/rcmdnk/vim_ahk/assets/1818935/421fa736-a458-42fd-bc6e-ec9fe6379f06)

If the mode is `1`, then `f` is printed as `f` is not implemented in vim_ahk, yet.

If you set `2` or `3`, then these non-implemented keys do not print.
(`3` is stricter mode in which mode `Ctrl`-X is also disabled if it is not implemented.)

**Comment by Shr4pNull** [comment]
That works, silly me. Sorry for wasting your time. 

I'm really enjoying your work btw

**Comment by rcmdnk** [comment]
No worries at all.
If you have any more questions, feel free to ask.
