### ISSUE TITLE
Use a different key to escape from Insert mode

### ISSUE THREAD

**Issue by bongbang** [rcmdnk/vim_ahk#97]
Is there  a way to do that? I want to use CapsLock instead of Esc, but a naive global `CapsLock::ESC` remapping doesn't work. I think I'd need to modify [`vim_state.ahk`](https://github.com/rcmdnk/vim_ahk/blob/08b735f7a42b266acbb06a1d69e4ef3bceebb3d2/lib/vim_state.ahk#L71), but I don't know how to do so.

**Comment by rcmdnk** [comment]
If you include vim_ahk from your script like
https://github.com/rcmdnk/vim_ahk?tab=readme-ov-file#scripts

then, if you add following code after including vim_ahk:

```
#If Vim.IsVimGroup()
a::Vim.State.HandleEsc()
#If
```

`a` in insert mode will change the mode into normal mode like `ESC`.

Following code for CapsLock may work:

```
#If Vim.IsVimGroup()
CapsLock::Vim.State.HandleEsc()
#If
```

It may not work as CaspLock sometime does not work with AHK well.
https://www.autohotkey.com/docs/v1/KeyList.htm#IME

For my environment, I swap the capslock to alt key by editing a registory.

**Comment by bongbang** [comment]
Many thanks.
